### PR TITLE
rebase

### PR DESCRIPTION
**Pull request by Quied**

### CODE REVIEW

**Review by gvozdvmozgu — APPROVED** [review]

**Comment by gvozdvmozgu** [comment]
@benfdking

**Comment by benfdking** [comment]
Sorry a few comflicts. 
image

**Comment by Quied** [comment]
> Sorry a few comflicts. image

This branch has the latest updates https://github.com/quarylabs/sqruff/pull/194

**Comment by gvozdvmozgu** [comment]
Can we close the PR?

**Pull request closed without merging**
