### PR TITLE
feat: Add benchmark for parsing queries

### PR DESCRIPTION
**Pull request by gvozdvmozgu**

### CODE REVIEW

**Comment by gvozdvmozgu** [comment]
Can we create a token for commenting with benchmark results?

https://github.com/boa-dev/criterion-compare-action/blob/59f4d964c5f19d7f13d36f5c0944b18ce6652cb0/main.js#L104-L108

**Comment by gvozdvmozgu** [comment]
!benchmark

**Comment by benfdking** [comment]
We can what do you need? The ability to read the repo or to comment on PRs? Could we achieve the same by just giving you the ability to work directly in the repo?

**Comment by gvozdvmozgu** [comment]
Yes, giving me direct access to the repo would solve the problem.

**Comment by benfdking** [comment]
@gvozdvmozgu invite sent. Let me know if that works. Sorry we only did this now.

**Comment by gvozdvmozgu** [comment]
can we merge this now

**Pull request merged**
