### PR TITLE
Include information of default dialect and dialect configuration

### PR DESCRIPTION
**Pull request by concur1**
Added information on the dialect and dialect configuration to the readme.

related issue: #740

### CODE REVIEW

**Comment by gvozdvmozgu** [comment]
You also need to update the `README.MD` file located at `editors/code`.

**Comment by benfdking** [comment]
```shell
cp README.md editors/code/README.md
```

For the update

**Comment by gvozdvmozgu** [comment]
I think we should inform users that they need to use 'sqruff' as the config key names.

**Comment by concur1** [comment]
> I think we should inform users that they need to use 'sqruff' as the config name and for the config key names.

So change:
```toml
[sqlfluff]
dialect = SQLite
```

to 
```toml
[sqruff]
dialect = SQLite
```
?

**Comment by gvozdvmozgu** [comment]
Yes, and also the file name. We have case-sensitive matching for the dialect name, so SQLite won't work.

**Comment by concur1** [comment]
Is Sqruff compatible with all Sqlfluff config files? Should I add a note around being able to copy over a config file from Sqlfluff?

**Comment by gvozdvmozgu** [comment]
We strive for backward compatibility with SQLFluff; some things might not work, but overall, yes.

**Comment by benfdking** [comment]
Thanks for the contribution

**Comment by concur1** [comment]
np, happy to help =)

**Pull request merged**
