### PR TITLE
feat: implementing the CV01 rule

### PR DESCRIPTION
**Pull request by benfdking**

### CODE REVIEW

**Comment by benfdking** [comment]
@gvozdvmozgu when you have time, do you know why the memory isn't working here?

**Comment by gvozdvmozgu** [comment]
It seems that the version of the grammar we are using incorrectly parses the expression.

The Python version (on which our version is based) and our version both produce an error:
```
== [pg.sql] FAIL
L:   1 | P:   1 | LT09 | Select targets should be on a new line unless there is
                       | only one select target.
                       | [layout.select_targets]
L:   1 | P:  33 |  PRS | Line 1, Position 33: Found unparsable section: '== 1 AND
                       | b != 2 AND c <> 3'
WARNING: Parsing errors found and dialect is set to 'ansi'. Have you configured your dialect correctly?
```

**Comment by benfdking** [comment]
@gvozdvmozgu cheers! good catch, should be done now.

**Comment by gvozdvmozgu** [comment]
It looks like the `default_config.cfg` needs to be updated.

**Comment by benfdking** [comment]
@gvozdvmozgu nice find!

**Review by gvozdvmozgu — APPROVED** [review]

**Pull request merged**
